name: Auto Data Collect Test

on:
  schedule:
    - cron: '5 7 * * *'  # 질문자님 가정: 한국시간 7시 5분
    - cron: '5 22 * * *' # 실제 깃허브 기준: 한국시간 7시 5분 (UTC 22시 5분)
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Time Test
        run: echo "Current UTC time is $(date -u)"
